sudo: false
language: objective-c
os: osx
cache: cocoapods
xcode_workspace: LocationManager/LocationManager.xcworkspace
xcode_scheme: LocationManagerExample
xcode_sdk: iphonesimulator12.0
osx_image: xcode9
podfile: LocationManager/Podfile

before_install:
  # - gem install cocoapods --no-ri --no-rdoc
  - gem install slather --no-document
  - gem install cocoapods
  - pod repo update
  
script: set -o pipefail && xcodebuild test -workspace LocationManager/LocationManager.xcworkspace -scheme LocationManagerExample -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=12.0'

after_success: 
    slather
